name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install node modules
      run: npm install
    - name: Run Unit tests
      run: npm run test:unit
    - name: Display softuni username
      run: echo "mim4eto02"
    
  start-and-ui-test:

    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install NPM dependencies
      run: npm install
    - name: Install Playwright Browsers
      run: npx playwright install 
    - name: Start the application
      run: npm run start &
    - name: Run the UI tests
      run: npm run test:ui
    
  deploy:
    runs-on: ubuntu-latest
    needs: start-and-ui-test
    steps:
      - name: Deploy to production
        uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
            service_id: ${{ secrets.MY_RENDER_SERVICE_ID }}
            api_key: ${{ secrets.MY_RENDER_API_KEY }}
            wait_deploy: true
